<?php
use Application\Model\Solicitante;
use Application\Model\Assunto;

$_SESSION['dados'] = ($_SESSION['dados'] ?? []);
$solicitante = $_SESSION['dados']['solicitante'] ?? new Solicitante([]);
$assunto = $_SESSION['dados']['assunto'] ?? new Assunto([]);
?>
<h1>Sistema de Atendimento a Demandas</h1>
	<?php
		if (isset($_SESSION['mensagem'])) :
	?>
	<p>
		<?=$_SESSION['mensagem']?>
	</p>			    
	<?php
        unset($_SESSION['mensagem']);
	endif;	
	?>
	<form method="post" action="<?=$this->url('application',['action' => 'processar'])?>">
		<div class="row">

			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="form-group">
					<label for="name">Nome do solicitante</label>
					<input type="text" name="nome" value="<?=$solicitante->nome?>" id="name" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="cpf">CPF</label>
					<input type="text" name="cpf" autofocus="autofocus" maxlength="11" value="<?=$solicitante->cpf?>" id="cpf" class="form-control"/>
				</div>
			</div>


			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="cep">CEP</label>
					<input type="text" name="cep" value="<?=$solicitante->cep?>" maxlength="8" id="cep" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="city">Municipio</label>
					<input type="text" name="municipio" value="<?=$solicitante->municipio?>" id="city" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="state">UF</label>
					<input type="text" name="uf" value="<?=$solicitante->uf?>" maxlength="2" id="state" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="form-group">
					<label for="email">E-mail</label>
					<input type="email" name="email" value="<?=$solicitante->email?>" id="email" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="ddd">DDD</label>
					<input type="number" name="ddd" value="<?=$solicitante->ddd?>" maxlength="2" id="ddd" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12">
				<div class="form-group">
					<label for="phone">Telefone</label>
					<input type="text" name="telefone" value="<?=$solicitante->telefone?>" id="phone" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="form-group">
					<label for="message">Assunto</label>
					<input type="text" name="assunto" value="<?=$assunto->assunto?>" id="message" class="form-control"/>
				</div>
			</div>

			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="form-group">
					<label for="details">Detalhes</label>
					<textarea name="detalhes" rows="10" cols="50" id="details"  class="form-control"><?=$assunto->detalhes?></textarea>
				</div>
			</div>

			<?php
			if (isset($_SESSION['dados']['detalhes_gravados'])):
			?>
			<p>Foi encontrado um assunto igual na base de demandas com estes detalhes:</p>
			<p>
			<?=$_SESSION['dados']['detalhes_gravados']?>
			</p>
			<?php
				unset($_SESSION['dados']['detalhes_gravados']);
			endif;
			?>   

			<div class="col-lg-12 col-md-12 col-sm-12 text-center">
				<button type="submit" class="btn btn-primary" value="gravar">Submit</button>
			</div>
		</div>
	</form>
<?php
$_SESSION['dados'] = [];
?>